### PR TITLE
feat(data): update tokens object to remove dashboard-colors property and rename dashboard themes

### PR DESCRIPTION
**Pull request by clairedenning**
…
2) **Rename theme** DS dashboard-darkMode to DS dash-dark. 
3) **Rename theme** DS dashboard-lightMode to DS dash-light. 
4) **Add token** origin-colors (reference only).yang.010. 
5) **Change value** of dashboard-darkmode.background.surface from {origin-colors (reference only).gray.700} to {origin-colors (reference only).gray.800}. 
6) **Change value** of dashboard-darkmode.background.neutral from {origin-colors (reference only).yin.020} to {origin-colors (reference only).yang.010}

BREAKING CHANGE: The dasboard-colors property has been removed, the token values held within it have been moved to the root.

### CODE REVIEW

**Comment by clairedenning** [comment]
@edleeks87  and @DobroTora, please can you make sure that I'm correct when I say the "token values held within it have been moved to the ROOT".  Difficult to tell for sure in the plugin. Thanks

**Comment by edleeks87** [comment]
> @edleeks87 and @DobroTora, please can you make sure that I'm correct when I say the "token values held within it have been moved to the ROOT". Difficult to tell for sure in the plugin. Thanks

It looks like the `dashboard-color` values have now been moved to the given `dashboard-` themes than the root

**Review by edleeks87 — APPROVED** [review]

**Comment by DobroTora** [comment]
> > @edleeks87 and @DobroTora, please can you make sure that I'm correct when I say the "token values held within it have been moved to the ROOT". Difficult to tell for sure in the plugin. Thanks
> 
> It looks like the `dashboard-color` values have now been moved to the given `dashboard-` themes than the root

Exactly @edleeks87 I still feel the format of data - (for example format of the provided strings for design tokens values) should be emphasised, but I hope we will touch on that in our conversations.

**Review by DobroTora — APPROVED** [review]

**Pull request merged**
