### PR TITLE
feat(data): Add colors.utility.major.450 token for use in dark_alt ta…

### PR DESCRIPTION
**Pull request by clairedenning**
Add colors.utility.major.450 token for use in dark_alt table headers

### CODE REVIEW

**Comment by ljemmo** [comment]
@clairedenning the update looks fine and won't break any current components. Should this token reference a base / raw token? Looks like we are adding a hex code directly which might be incorrect?

**Review by ljemmo — CHANGES_REQUESTED** [review]
Value 450 needs to reference an origin token.

**Comment by clairedenning** [comment]
@luke I am an idiot. Will fix that now.

**Comment by ljemmo** [comment]
@clairedenning change looks good, merging into master.

**Review by ljemmo — APPROVED** [review]

**Pull request merged**
